// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;

    [RequiresSkill(typeof(PaperMillingSkill), 0)]      
    public partial class SignLandClaimPaperRecipe :
        RecipeFamily
    {
        public SignLandClaimPaperRecipe()
        {
            this.Initialize(Localizer.DoStr("Sign Land Claim Papers"), typeof(SignLandClaimPaperRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "Sign Land Claim Papers",
                    Localizer.DoStr("Sign Land Claim Papers"),
                    new IngredientElement[]
                    {
                    new IngredientElement(typeof(UnsignedLandClaimPaperItem), 1, true),
					new IngredientElement(typeof(GoldBarItem), 1, true), 					
                    },
                    new CraftingElement[]
                    {
                    new CraftingElement<PropertyClaimItem>(1), 
                    }
                )
            };

			this.ExperienceOnCraft = 0; 

            this.LaborInCalories = CreateLaborInCaloriesValue(100); 
            this.CraftMinutes = CreateCraftTimeValue(30);     
            this.Initialize(Localizer.DoStr("Sign Land Claim Papers"), typeof(SignLandClaimPaperRecipe));

            CraftingComponent.AddRecipe(typeof(CarpentryTableObject), this);
        }
    }
}
