// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;

    [RequiresSkill(typeof(PaperMillingSkill), 1)]      
    public partial class UnsignedLandClaimPaperRecipe :
        RecipeFamily
    {
        public UnsignedLandClaimPaperRecipe()
        {
            this.Initialize(Localizer.DoStr("Print Land Claim Papers"), typeof(UnsignedLandClaimPaperRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "Print Land Claim Papers",
                    Localizer.DoStr("Print Land Claim Papers"),
                    new IngredientElement[]
                    {
                    new IngredientElement(typeof(PaperItem), 300, typeof(PaperMillingSkill), typeof(PaperMillingLavishResourcesTalent)),    
                    },
                    new CraftingElement[]
                    {
                    new CraftingElement<UnsignedLandClaimPaperItem>(1), 
                    }
                )
            };


            this.ExperienceOnCraft = 50;  

            this.LaborInCalories = CreateLaborInCaloriesValue(10000, typeof(PaperMillingSkill), typeof(UnsignedLandClaimPaperRecipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(UnsignedLandClaimPaperRecipe), this.UILink(), 30, typeof(PaperMillingSkill), typeof(PaperMillingFocusedSpeedTalent), typeof(PaperMillingParallelSpeedTalent));     
            this.Initialize(Localizer.DoStr("Print Land Claim Papers"), typeof(UnsignedLandClaimPaperRecipe));

            CraftingComponent.AddRecipe(typeof(CarpentryTableObject), this);
        }
    }

    [Serialized]
    [LocDisplayName("Unsigned Land Claim Papers")]
    [Weight(100)]      
    [Fuel(100)][Tag("Fuel")]          
    [Currency] 
    [Ecopedia("Items", "Products", createAsSubPage: true, display: InPageTooltip.DynamicTooltip)]                                                                           
    [Tag("Burnable Fuel", 1)]                                 
    public partial class UnsignedLandClaimPaperItem :
    Item                                    
    {
        public override LocString DisplayDescription { get { return Localizer.DoStr("Bureaucracy in paper form. Useless until signed."); } }
    }
}
